package com.reflect;

import java.io.ByteArrayOutputStream;
import java.util.zip.*;

public class Compress {

    public static void main(String[] args) {

        String str = "[\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 371.587,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 112\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 371.587,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 28\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 107.41,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 1\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 107.41,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 34\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 264.177,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 10\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 72.403,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 23\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 72.403,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 102\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 220.079,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 2\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 220.079,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 41\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 57.865,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 260\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 350.347,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 380\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -86.17,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 21\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -64.458,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 82\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 0.55,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 65\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -63.908,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 368\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 0.843,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 371\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 0.843,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 85\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -149.235,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 4\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -29.597,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 363\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -29.597,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 98\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -6.081,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 56\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -398.267,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 374\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -357.431,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 32\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -40.836,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 87\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -583.18,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 139\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": 7.406,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 75\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -590.586,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 7\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -590.586,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 41571\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -590.586,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 15\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -590.586,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 16\n"
                + "  },\n"
                + "  {\n"
                + "    \"unit\": \"Millions\",\n"
                + "    \"periodEndDate\": \"2016-12-31\",\n"
                + "    \"symbol\": \"1491424D\",\n"
                + "    \"value\": -590.586,\n"
                + "    \"filingDate\": \"2017-02-23\",\n"
                + "    \"calendarYear\": 2016,\n"
                + "    \"calendarQuarter\": 4,\n"
                + "    \"currency\": \"USD\",\n"
                + "    \"dataItemId\": 379\n"
                + "  }\n"
                + "]";
        byte[] bytes = str.getBytes();

        System.out.println(bytes.length);

        byte[] compressedBytes = compress(bytes);
        System.out.println(compressedBytes.length);

        try {
            System.out.println(uncompress(compressedBytes).length);
        } catch (DataFormatException e) {
            e.printStackTrace();
        }
    }

    public static byte[] compress(byte input[]) {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        Deflater compressor = new Deflater(1);
        try {
            compressor.setInput(input);
            compressor.finish();
            final byte[] buf = new byte[2048];
            while (!compressor.finished()) {
                int count = compressor.deflate(buf);
                bos.write(buf, 0, count);
            }
        } finally {
            compressor.end();
        }
        return bos.toByteArray();
    }

    public static byte[] uncompress(byte[] input) throws DataFormatException {
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        Inflater decompressor = new Inflater();
        try {
            decompressor.setInput(input);
            final byte[] buf = new byte[2048];
            while (!decompressor.finished()) {
                int count = decompressor.inflate(buf);
                bos.write(buf, 0, count);
            }
        } finally {
            decompressor.end();
        }
        return bos.toByteArray();
    }
}
